version: '3.5'

services:
  database_mariadb:
      image: mariadb
      container_name: mariadb_amazon
      environment: 
        - MYSQL_ROOT_PASSWORD=password
        - MYSQL_DATABASE=testeb
        - MYSQL_USER=user
        - MYSQL_PASSWORD=user
      ports:
        - "33060:3306"
      restart: on-failure
  
  nginx_amazon:
    container_name: amazon-nginx_php-fpm
    cap_add:
      - SYS_ADMIN
    security_opt:
      - seccomp:unconfined
    links:
      - database_mariadb
    ports:
      - "80:80/tcp"
      - "443:443/tcp"
      - "3306:3306"
    tmpfs:
      - /run
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    environment:
      - TZ=Europe/Lisbon
      - container=docker
    build: 
      context: ./
      dockerfile: Dockerfile

  adminer:
    container_name: adminer
    image: adminer
    restart: on-failure
    links:
      - database_mariadb
    ports:
      - 8090:8080

    restart: on-failure
    #OPTIONS ON CONTAINER  
    stdin_open: true
    tty: true
    #privileged: true


